// Writes docs/shot-list.md: every "Photo to come" frame on the slide pages, page by page, with
// the frame ratio and the brief written inside it. Pomi can shoot from it, and each filled frame
// only needs its photo ref added in the page's JSON (see src/assets/gallery/catalogue.json).
//
// Usage: node scripts/shot-list.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { effectiveRatio, pageSlots, resolveLayout } from "../src/lib/sections.ts";

const learn = JSON.parse(readFileSync("src/content/seed/learn.json", "utf8"));
const pages = JSON.parse(readFileSync("src/content/seed/pages.json", "utf8"));

// Safety and Aftercare first: they are the pages people land on before booking, and their
// headers are the first thing a phone shows.
const all = [
  ...pages.map((p) => ({ title: p.title, url: `/${p.slug}`, lead: p.lead, sections: p.sections, cover: undefined })),
  ...learn.map((a) => ({ title: a.title, url: `/learn/${a.slug}`, lead: a.cover ? undefined : a.lead, sections: a.sections ?? [], cover: a.cover })),
];

let total = 0;
const out = [
  "# Shot list",
  "",
  "Every empty frame on the info pages, written inside the frame on the site as \"Photo to come\".",
  "Generated by `node scripts/shot-list.mjs` from the page content; run it again after a change.",
  "Shoot to the ratio given (a 5:2 strip is wide and short). Once a photo is in the gallery,",
  "add its `photo.ref` to the slot in `src/content/seed/pages.json` or `learn.json`.",
  "",
];
for (const page of all) {
  const slots = pageSlots({ lead: page.lead, sections: page.sections }).filter((x) => !x.slot.photo?.ref);
  if (!slots.length) continue;
  total += slots.length;
  out.push(`## ${page.title.replace(/\.$/, "")} (${page.url}), ${slots.length} frame${slots.length === 1 ? "" : "s"}`, "");
  for (const { role, slot, index } of slots) {
    const where = index < 0 ? "Page header" : page.sections[index].heading ?? `Section ${index + 1}`;
    const layout = index < 0 ? "lead" : resolveLayout(page.sections[index]);
    const ratio = effectiveRatio(role, slot.ratio).replace(" / ", ":");
    out.push(`- **${where.replace(/\.$/, "")}** (${layout}, ${ratio}): ${slot.shot}`);
  }
  out.push("");
}
out.splice(7, 0, `${total} frames in all.`, "");
writeFileSync("docs/shot-list.md", out.join("\n"));
console.log(`docs/shot-list.md: ${total} frames`);
